version: '3.3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/social-network
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
      - ./public:/app/public

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: